title: "Winger Solutions B. V."
description: "Custom software solutions, web development & consulting"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dbwinger.github.io" # Your GitHub Pages URL

# Theme
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# SEO settings
lang: en_US
author: Winger Solutions B. V.

# Social links (optional)
github_username: dbwinger # Update with your GitHub username
email: info@wingersolutions.nl # Update with your email
