title: "Winger Solutions B. V."
description: "Custom software solutions, web development & consulting"
baseurl: "" # Empty for custom domain
url: "https://wingersolutions.nl" # Your custom domain

# Multilingual setup
languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["assets", "CNAME", "README.md"]

# Language-specific content
t:
  en:
    title: "Winger Solutions B. V."
    description: "Custom software solutions, web development & consulting"
    nav:
      home: "Home"
      about: "About" 
      contact: "Contact"
  nl:
    title: "Winger Solutions B. V."
    description: "Maatwerk software oplossingen, webontwikkeling & advies"
    nav:
      home: "Home"
      about: "Over"
      contact: "Contact"

# Theme
remote_theme: pages-themes/hacker

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# SEO settings
lang: en_US
author: Winger Solutions B. V.

# Social links (optional)
github_username: dbwinger # Update with your GitHub username
email: info@wingersolutions.nl # Update with your email
